/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.intercom;

import android.os.Build;

import androidx.annotation.NonNull;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.TiApplication;

import io.intercom.android.sdk.Intercom;
import io.intercom.android.sdk.IntercomContent;
import io.intercom.android.sdk.IntercomError;
import io.intercom.android.sdk.IntercomSpace;
import io.intercom.android.sdk.IntercomStatusCallback;
import io.intercom.android.sdk.UserAttributes;
import io.intercom.android.sdk.identity.Registration;
import io.intercom.android.sdk.push.IntercomPushClient;

@Kroll.module(name="TitaniumIntercom", id="ti.intercom")
public class TitaniumIntercomModule extends KrollModule {

	private IntercomPushClient pushClient = new IntercomPushClient();
	private static boolean isInitialized = false;
	private static String apiKey = null;
	private static String appId = null;

	private static void initialize() {
		if (isInitialized) {
			Log.d("Intercom", "Intercom is already initialized, ignoring re-initializing.");
			return;
		}

		if (apiKey != null && appId != null) {
			Intercom.initialize(TiApplication.getInstance(), apiKey, appId);
			isInitialized = true;
			Log.d("Intercom", "Intercom has been initialized");
		} else {
			Log.d("Intercom", "Intercom could not be initialized");
		}
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		isInitialized = false;
		apiKey = app.getAppProperties().getString("intercom-android-api-key", null);
		appId = app.getAppProperties().getString("intercom-app-id", null);

		// Defer the initialization on Android 12 and 13 to avoid ANRs as suggested by the Intercom Support team.
		// It would further require that the Intercom.initialize() is called before any other Intercom API is used.
		if (Build.VERSION.SDK_INT >= 31 && Build.VERSION.SDK_INT <= 33) {
			Intercom.registerForLaterInitialisation(app);
		} else {
			initialize();
		}
	}

	@Kroll.method
	public void configure(KrollDict params) {
		apiKey = params.getString("apiKey");
		appId = params.getString("appId");
		initialize();
	}

	@Kroll.setProperty
	public void setVisible(boolean visible) {
		Intercom.client().setLauncherVisibility(visible ? Intercom.Visibility.VISIBLE : Intercom.Visibility.GONE);
	}

	@Kroll.setProperty
	public void setBottomPadding(int bottomPadding) {
		Intercom.client().setBottomPadding(bottomPadding);
	}

	@Kroll.setProperty
	public void setUserHash(String userHash) {
		if (userHash != null) {
			Intercom.client().setUserHash(userHash);
		}
	}

	@Kroll.method
	public void registerUser(@Kroll.argument(optional = true) KrollDict user) {
		if (user == null) {
			Intercom.client().loginUnidentifiedUser(new IntercomStatusCallback() {
				@Override
				public void onSuccess() {
					// Add success callback?
				}

				@Override
				public void onFailure(@NonNull IntercomError intercomError) {
					// Add error callback?
				}
			});
			return;
		}

		String userId = user.getString("identifier");
		String email = user.getString("email");
		Registration userRegistration = Registration.create().withUserId(userId);

		if (email != null) {
			userRegistration = userRegistration.withEmail(email);
		}

		Intercom.client().loginIdentifiedUser(userRegistration, new IntercomStatusCallback() {
			@Override
			public void onSuccess() {
				// Add success callback?
			}

			@Override
			public void onFailure(@NonNull IntercomError intercomError) {
				// Add error callback?
			}
		});
	}

	@Kroll.method
	public void updateUser(KrollDict user) {
		String id = user.getString("id");
		String email = user.getString("email");
		String name = user.getString("name");
		String locale = user.getString("locale");
		KrollDict customAttributes = user.getKrollDict("customAttributes");

		UserAttributes.Builder userAttributes = new UserAttributes.Builder();

		if (id != null) {
			userAttributes.withUserId(id);
		}

		if (email != null) {
			userAttributes.withEmail(email);
		}

		if (name != null) {
			userAttributes.withName(name);
		}

		if (locale != null) {
			userAttributes.withLanguageOverride(locale);
		}

		if (customAttributes != null) {
			userAttributes.withCustomAttributes(customAttributes);
		}

		Intercom.client().updateUser(userAttributes.build(), new IntercomStatusCallback() {
			@Override
			public void onSuccess() {
				// Add success callback?
			}

			@Override
			public void onFailure(@NonNull IntercomError intercomError) {
				// Add error callback?
			}
		});
	}

	@Kroll.method
	public void logout() {
		Intercom.client().logout();
	}

	@Kroll.method
	public void presentMessenger(@Kroll.argument(optional = true) String message) {
		if (message != null) {
			Intercom.client().displayMessageComposer(message);
		} else {
			Intercom.client().present();
		}
	}

	@Kroll.method
	public void presentSupportCenter() {
		Intercom.client().present();
	}

	@Kroll.method
	public void presentMessageComposer(String message) {
		presentMessenger(message);
	}

	@Kroll.method
	public void presentCarousel(String carouselId) {
		Intercom.client().presentContent(new IntercomContent.Carousel(carouselId));
	}

	@Kroll.method
	public void presentHelpCenter() {
		Intercom.client().present(IntercomSpace.HelpCenter);
	}

	@Kroll.method
	public void updatePushToken(String pushToken) {
		if (pushToken == null) {
			pushToken = ""; // Reset token to empty string if deleted
		}

		pushClient.sendTokenToIntercom(TiApplication.getInstance(), pushToken);
	}
}

